import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { LoginButton } from '../components/login-button'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Next SUZURI API Starter!</h1>

        <p className={styles.description}>
          Next.js, NextAuth.jsでSUZURI
          APIのOAuthを使うサンプルプロジェクトです。
        </p>

        <LoginButton />

        <div className={styles.grid}>
          <Link href="/secret" className={styles.card}>
            <h2>ログイン必須のページ &rarr;</h2>
            <p>ログインしていない時はログイン画面に遷移します</p>
          </Link>

          <Link href="/try-api" className={styles.card}>
            <h2>API取得の例 &rarr;</h2>
            <p>公開APIから情報を取得して表示します</p>
          </Link>

          <Link href="/create" className={styles.card}>
            <h2>APIでMaterialを作る例 &rarr;</h2>
            <p>画像ファイルからMaterialを作成します</p>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
